# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fba2c986a529e7302cb28fcc4b5cb52c889b0e639b73d25035fd3fa96a65ced30233c7c2cf4a6ec4e8636dbe86cdb099f50f94a341d8a744b848ff391ac650

test:
  secret_key_base: 4ea76fdf12e4e74b74188641c59c7cb0fa7c5f46a33dc0492086a94e89900f815526d7d8693973b905ffb0e169b3dca7e83c1d5e139617f76dbb9494eac6b7a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
